### ISSUE TITLE
建议～～

### ISSUE THREAD

**Issue by miniflycn** [Focus-Team/focus-team.github.io#3]
目前我们团队也搭建了我们的前端社区，当然希望别的团队也能加入进来，看看能不能和我们一起来建设我们的社区呢？

社区地址：http://imweb.io

当然也可以选择自己搭建，如有需要请联系，litten君（@litten）

**Comment by FrankFang** [comment]
有 GitHub 同步功能不，一键关联就好了。

**Comment by miniflycn** [comment]
目前的写作体验近似与马克飞象，应该比github写起来体验好点。

**Comment by FrankFang** [comment]
信息有误，帐号无法被激活。  邮箱 frankfang1990(在)gmail  @miniflycn

**Comment by miniflycn** [comment]
@litten
